services:
  gateway.api:
    image: gateway.api
    container_name: Gateway.Api
    build:
      context: .
      dockerfile: Gateway.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=${GATEWAY_API_CERT_PASS}
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=certs/gateway.api.pfx
    ports:
      # - "5001:5001"
      - "5000:5000"
    volumes:
      - ./certs:/app/certs:ro
    networks:
      - proxybackend

  chat.service:
    image: chat.service
    container_name: Chat.Service
    build:
      context: .
      dockerfile: Chat.Service/Chat.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:3000
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=${CHAT_SERVICE_CERT_PASS}
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=certs/chat.service.pfx
      - AES_IV=${AES_IV}
      - AES_KEY=${AES_KEY}
    depends_on:
      - chat.db
    ports:
      # - "3001:3001"
      - "3000:3000"
    secrets:
      - jwt-secret-key
    volumes:
      - ./certs:/app/certs:ro
    networks:
      - proxybackend

  chat.db:
    image: postgres:latest
    container_name: Chat.DB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chatdb
    volumes:
      - chat-db-data:/var/lib/postgresql/data
    restart: always
    command: "-c logging_collector=on"
    ports:
      - "3050:5432"
    networks:
      - proxybackend

  web.client:
    image: web.client
    container_name: Web.Client
    build:
      context: Web.Client
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./Web.Client:/app
      - /app/node_modules
    command: npm start

  identity.service:
    image: identity.service
    container_name: Identity.Service
    build:
      context: Identity.Service
      dockerfile: Dockerfile
      args:
        - BUILD_TYPE=Debug # or Release
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=identitydb
    restart: always
    depends_on:
      - identity.db
    ports:
      - "4000:4000"
    secrets:
      - jwt-secret-key
    networks:
      - proxybackend

  identity.db:
    image: postgres:latest
    container_name: Identity.DB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=identitydb
    restart: always
    command: "-c logging_collector=on"
    ports:
      - "4050:5432"
    volumes:
      - identity-db-data:/var/lib/postgresql/data
    networks:
      - proxybackend

volumes:
 chat-db-data:
 identity-db-data:

secrets:
  jwt-secret-key:
    file: ./.jwt-secret

networks:
  proxybackend:
    name: proxybackend
    driver: bridge