version: '3.8'

services:
  chat.service:
    image: chat.service
    container_name: Chat.Service
    build:
      context: ./Chat.Service
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=3000
    ports:
      - "3000:3000"

  web.client:
    image: web.client
    container_name: Web.Client
    build:
      context: ./Web.Client
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./Web.Client:/app
      - /app/node_modules
    command: npm start