name: Build and Deploy on Push

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Chat.Service/**'
      - 'Identity.Service/**'
      - 'Web.Client/**'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Chat.Service
      - name: Build Chat.Service
        run: |
          docker build --no-cache -t chat.service -f Chat.Service/Chat.Api/Dockerfile .

      # Build Identity.Service
      - name: Build Identity.Service
        run: |
          docker build --no-cache -t identity.service -f Identity.Service/Dockerfile Identity.Service

      # Build Web.Client
      - name: Build Web.Client
        run: |
          docker build --no-cache -t web.client -f Web.Client/Dockerfile Web.Client

      # Build Gateway.Api
      - name: Build Gateway.Api
        run: |
          docker build --no-cache -t gateway.api -f Gateway.Api/Dockerfile .

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .jwt-secret file
        env:
          JWT_SECRET_CONTENT: ${{ secrets.JWT_SECRET_CONTENT }}
        run: |
          mkdir -p /home/swaggoo/actions-runner/_work/Cipher/Cipher
          echo "$JWT_SECRET_CONTENT" > /home/swaggoo/actions-runner/_work/Cipher/Cipher/.jwt-secret

      - name: Copy .env and certs
        run: |
          cp /home/swaggoo/actions-runner/_work/.env /home/swaggoo/actions-runner/_work/Cipher/Cipher
          cp -r /home/swaggoo/actions-runner/_work/certs /home/swaggoo/actions-runner/_work/Cipher/Cipher

      - name: Change to Cipher directory and Deploy services
        run: |
          docker stop $(docker ps -aq)
          docker rm $(docker ps -aq)
          docker rmi $(docker images -q)
          docker volume rm $(docker volume ls -q)

          # Start the new containers
          docker compose up -d
